In [3]:
from sklearn.datasets import fetch_20newsgroups

In [4]:
data = fetch_20newsgroups()

In [6]:
data.target_names

AttributeError: 'list' object has no attribute 'shape'

In [7]:
data.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR', 'description'])

In [11]:
type(data.data)
data.data[:2]

["From: lerxst@wam.umd.edu (where's my thing)\nSubject: WHAT car is this!?\nNntp-Posting-Host: rac3.wam.umd.edu\nOrganization: University of Maryland, College Park\nLines: 15\n\n I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.\n\nThanks,\n- IL\n   ---- brought to you by your neighborhood Lerxst ----\n\n\n\n\n",
 "From: guykuo@carson.u.washington.edu (Guy Kuo)\nSubject: SI Clock Poll - Final Call\nSummary: Final call for SI clock reports\nKeywords: SI,acceleration,clock,upgrade\nArticle-I.D.: shelley.1qvfo9INNc3s\nOrganization: University of Washington\nLines: 

In [15]:
data.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [16]:
train= fetch_20newsgroups(subset='train', categories=data.target_names)

In [21]:
test= fetch_20newsgroups(subset='test', categories=data.target_names)

In [22]:
train.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR', 'description'])

In [26]:
len(train.target), len(train.data)

(11314, 11314)

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn.multiclass import OneVsRestClassifier
import numpy as np

#ovr = OneVsRestClassifier(MultinomialNB())

#model = make_pipeline(TfidfVectorizer, MultinomialNB)
#model.fit(rcv1_train.data, rcv1_train.target)
#model = MultinomialNB()
#model.fit(rcv1_train.target, rcv1_train.target_names)
#ovr.fit(rcv1_train.target, rcv1_train.target_names)# Toy dataset where features correspond directly to labels.
X = np.array([[0, 4, 5], [0, 5, 0], [3, 3, 3], [4, 0, 6], [6, 0, 0]])
y = np.array([[0, 1, 1],
              [0, 1, 0],
              [1, 1, 1],
              [1, 0, 1],
              [1, 0, 0]])
model = OneVsRestClassifier(MultinomialNB()).fit(X, y)

if False:
    for base_clf in (MultinomialNB(), LinearSVC(random_state=0),
                     LinearRegression(), Ridge(),
                     ElasticNet(), Lasso(alpha=0.5)):
        clf = OneVsRestClassifier(base_clf).fit(X, y)
        y_pred = clf.predict([[0, 4, 4]])[0]
        assert_array_equal(y_pred, [0, 1, 1])
        assert_true(clf.multilabel_) 

In [7]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.multiclass import OneVsRestClassifier
import numpy as np

X = np.array([[0, 4, 5], 
              [0, 5, 0], 
              [3, 3, 3], 
              [4, 0, 6], 
              [6, 0, 0]])
y = np.array([[0, 1, 1],
              [0, 1, 0],
              [1, 1, 1],
              [1, 0, 1],
              [1, 0, 0]])
print(X.shape, y.shape)
#X = np.array([[0, 4, 5,6], [0, 5, 0,7], [3, 3, 3,0], [4, 0, 6,1], [6, 0, 0,2]])
model = OneVsRestClassifier(MultinomialNB()).fit(X, y)
#model = MultinomialNB().fit(X, y)

#y_pred = model.predict([[0, 4, 4]])[0]


(5, 3) (5, 3)


In [32]:
y_pred

array([0, 1, 1])

In [34]:
X.shape, y.shape

((5, 3), (5, 3))

In [37]:
import nltk

In [ ]:
model = nltk.classifier.NaiveBayese

In [1]:
import pandas as pd

list_list=[[1,2,3],['a','b','c']]
pd.DataFrame(list_list)

0  1  2
0  1  2  3
1  a  b  c

In [6]:
import p6_util

file_name="../data/train_StackOverFlow_BodyTitleTags.csv"
ser_sof_tags_train=pd.read_csv(file_name)['Tags']
print(ser_sof_tags_train.shape)
list_list_tags  = ser_sof_tags_train.apply(p6_util.clean_marker_text, leading_marker='<', trailing_marker='>').tolist()

(24604,)


In [7]:
#def get_list_unique_tag()
list_ref_tags = list()
for list_tags in list_list_tags :
    list_ref_tags += [tag for tag in list_tags]

list_ref_tags = list(set(list_ref_tags))
print(len(list_ref_tags))

6436


In [8]:
list_list_tags
list_ = list()
for list_tag in list_list_tags :
    for tag in list_tag :
        list_.append(tag)
list_unique_tag = list(set(list_))
len(list_unique_tag)

6436

In [1]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()

In [12]:
import pandas as pd
file_name="../data/StackOverFlowTags.csv"
df_sof_tags=pd.read_csv(file_name)
df_sof_tags.shape

#lb.fit_transform(['yes', 'no', 'no', 'yes'])

(50000, 2)

In [ ]:
list_unique_tag = [tag for tag in df_sof_tags.TagName.apply(lambda x:str(x))]
print(len(list_unique_tag))

In [15]:
import numpy as np
row = np.where(arr_filter[1]==4471)[0][0]

In [27]:
lb.classes_[71],np.where(arr_filter[1]==71)[0][0],list_unique_tag[np.where(arr_filter[1]==71)[0][0]]

('on-location-changed', 99, 'on-location-changed')

In [29]:
def get_tag_from_encoder(lb, tag_value) :
    row = np.where(arr_filter[1]==tag_value)[0][0]
    return lb.classes_[row]


In [33]:
get_tag_from_encoder(lb,89) in list_unique_tag[:100]

True

In [46]:
ser_sof_tags_train

0    <c#><floating-point><type-conversion><double><...
1               <html><css><css3><internet-explorer-7>
Name: Tags, dtype: object

In [42]:
import p5_util
import p6_util

file_name="../data/train_StackOverFlow_BodyTitleTags.csv"
ser_sof_tags_train=pd.read_csv(file_name)['Tags']
print(ser_sof_tags_train.shape)


list_list_tags_train  \
    = ser_sof_tags_train.apply(p6_util.clean_marker_text, leading_marker='<', trailing_marker='>').tolist()
print(len(list_list_tags_train))

list_ref_tags = list()
for list_tags in list_list_tags_train :
    list_ref_tags += [tag for tag in list_tags]

list_ref_tags = list(set(list_ref_tags))
print(len(list_ref_tags))


(24604,)
24604
6436


In [44]:
encoder = lb.fit_transform(list_ref_tags)

In [49]:
import numpy as np

arr_filter = np.where(encoder>0)
arr_filter[0][:10],arr_filter[1][:10]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([6115,  776, 5165, 1117,  752, 6052,   31, 3140, 1683, 4420]))

In [43]:
encoder = lb.fit_transform(list_unique_tag[:100])

<class 'list'>
