<!--NOTEBOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="./figures/LogoOpenclassrooms.png">
<font size="4">
<p>
Cette étude a été réalisée dans le cadre du 4eme projet de ma formation Datascientist dispensée en MOOC par 
**<font color='blus'>Openclassrooms / écoles Centrale-Supélec</font>**.
</p>    

<p>
Ce notebook présente  un modèle de prédictions des retards d'avions implémenté dans le ficher <font color='blue'>P4_ModelBuilder.py</font>.
</p>
<p>
Il utilise les résultats de l'analyse exploratoire implémentée dans le notebook <font color='blue'>P4_3.ipynb</font>.
</p>

<p>
Le modèle est basé sur les données fournies par le site :
</p>
<p>
https://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=236&DB_Short_Name=On-Time
</p>
<p>
</p>
</font>

# <font color='blus'> Mise au point du composant </font><font color='blue'>P4_ModelBuilder</font>

In [1]:
from P4_ModelBuilder import *
import LinearDelayPredictor

In [2]:
help (P4_ModelBuilder)

Help on class P4_ModelBuilder in module P4_ModelBuilder:

class P4_ModelBuilder(builtins.object)
 |  This class aims to build data model for project P4 for Openclassrooms 
 |  course of datascientist training.
 |  Services provided by this class are :
 |     -> It builds computational data issues from CSV files.
 |     -> It proceeds to data preparation : data cleaning and scaling.
 |     -> It builds computational models from linear regression algorithms 
 |        issued fro scikitlearn library.
 |     -> It builds component in charge of flight delay predictions : LinearDelayPredictor
 |        LinearDelayPredictor class aims to be deployed for production.
 |     
 |  Instructions flow :
 |  -------------------
 |     main()
 |     |
 |     +-->load_and_clean(list_col_keep)
 |     |   |
 |     |   +--> < Boucle sur les fichiers a lire >
 |     |   |    |
 |     |   |    +--> < loading file into temp dataframe>
 |     |   |    |
 |     |   |    +--> < cleaning  temp dataframe regardin

In [3]:
path_name = "../outside_p4/data/Dataset+Projet+4_2/"
year = 2016
oP4_ModelBuilder = P4_ModelBuilder(path_name,year)
oP4_ModelBuilder.is_route_in_model = True
oP4_ModelBuilder.is_delay_outlier_removed = True
oP4_ModelBuilder.dict_delay_splitted = {'neg':0,'pos':0}
oP4_ModelBuilder.is_route_restricted = False
oP4_ModelBuilder.is_low_memory = True
#oP4_ModelBuilder._modulo_month = 3
#oP4_ModelBuilder.list_carrier_id = ['DL', 'AA', 'AS', 'B6', 'EV', 'F9', 'VX', 'WN', 'OO', 'UA', 'HA', 'NK']
#oP4_ModelBuilder.list_carrier_id = [19790, 19805, 19930, 20409, 20366, 20436, 21171, 19393, 20304, 19977, 19690, 20416]
#oP4_ModelBuilder.list_carrier_id = [19790]
oP4_ModelBuilder.list_carrier_id = list()


# When reading files, get a fraction of row dataframes.
oP4_ModelBuilder.fract_data = -1

# Get a fraction of dataframe rows for user tests dataframes.
oP4_ModelBuilder.frac_test = 0.001


## <font color='blue'>*Méthode load_and_clean()*</font>

In [4]:
list_col_keep = [
 'CRS_DEP_TIME'
,'ORIGIN_AIRPORT_ID'
,'DEST_AIRPORT_ID'          
,'ORIGIN_CITY_NAME'
,'DEST_CITY_NAME'             
,'ARR_DELAY'
,'AIRLINE_ID'    
,'MONTH'
,'DAY_OF_MONTH'
,'DAY_OF_WEEK'
,'CARRIER'
,'CRS_ARR_TIME'    
,'FL_NUM'    
,'ORIGIN_STATE_ABR'
,'DEST_STATE_ABR'    
]

#-------------------------------------------------------------------------
# These features are used for user test 
#-------------------------------------------------------------------------
list_for_user_test =['MONTH','DAY_OF_MONTH','DAY_OF_WEEK'\
      , 'CRS_DEP_TIME','AIRLINE_ID','ORIGIN_CITY_NAME','DEST_CITY_NAME'\
      ,'ARR_DELAY','CARRIER','CRS_ARR_TIME','FL_NUM','ORIGIN_STATE_ABR','DEST_STATE_ABR']

#-------------------------------------------------------------------------
# These features are excluded from data model
#-------------------------------------------------------------------------
list_excluded = ['WEEK_OF_MONTH','CARRIER','CRS_ARR_TIME','FL_NUM']

#list_month = ['01','02','03','04','05','06','07','08','09','10','11','12']
list_month = ['01','02','03','04']
list_month = ['01']
list_skip_rows_04 = [121011,386248,388290,389370,389547,453857]
dict_skip_rows = dict()
dict_skip_rows['01'] = None
dict_skip_rows['02'] = None
dict_skip_rows['03'] = None
dict_skip_rows['04'] = list_skip_rows_04
dict_skip_rows['05'] = None
dict_skip_rows['06'] = None
dict_skip_rows['07'] = None
dict_skip_rows['08'] = None
dict_skip_rows['09'] = None
dict_skip_rows['10'] = None
dict_skip_rows['11'] = None
dict_skip_rows['12'] = None
list_for_cleaning = ['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK'\
                     ,'AIRLINE_ID','ORIGIN_AIRPORT_ID', 'DEST_AIRPORT_ID','CRS_DEP_TIME', 'ARR_DELAY']
oP4_ModelBuilder.load_and_clean(list_month,list_col_keep,list_for_cleaning,dict_skip_rows=dict_skip_rows)
oP4_ModelBuilder.print()

Month 01 loaded!
Columns targeted for nan : []

MONTH : ...
(433298, 15)
(433298, 15)
[1]
[1]
[1]
[1]
MONTH : Done!


DAY_OF_MONTH : ...
(433298, 15)
(433298, 15)
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31  1  2  3  4  5]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31  1  2  3  4  5]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31  1  2  3  4  5]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31  1  2  3  4  5]
DAY_OF_MONTH : Done!


DAY_OF_WEEK : ...
(433298, 15)
(433298, 15)
[3 4 5 6 7 1 2]
[3 4 5 6 7 1 2]
[3 4 5 6 7 1 2]
[3 4 5 6 7 1 2]
DAY_OF_WEEK : Done!


AIRLINE_ID : ...
(433298, 15)
(433298, 15)
[19805 19930 20409 19790 20436 19690 20416 20366 20304 19977 21171 19393]
[19805 19930 20409 19790 20436 19690 20416 20366 20304 19977 21171 19393]
[19805 19930 20409 19790 20436 19690 20416 20366 20304 19977 21171 19393]
[19805 19930 20409 19790 20436 1969

In [7]:
oP4_ModelBuilder.print()


-------------------------------------------------------------
Data set year : ......................... : 2016
Low memory flag : ....................... : True
Data model dimensions : ................. :(433298, 15)
Route in model : ........................ : True
Removing outliers : ..................... : True
Percent removed outliers : .............. : 0.00
Split delay config ...................... : {'neg': 0, 'pos': 0}
Carrier in model : ...................... : False

Qualitative features list ............... : []
Quantitative features list .............. : {}
Target features list .................... : None
Excluded features list .................. : []
Periodic features list .................. : []
References features list ................ : None
Number of columns for quantitative data . : 0
Test size ratio ......................... : 0.3
Features processor ...................... : {}
Modulo for loading file  ................ :  4
Fraction of data  ....................... :  -

## <font color='blue'>Méthode *data_build()*</font>

In [8]:
oP4_ModelBuilder._df.shape, oP4_ModelBuilder._df.columns

((433298, 15), Index(['CRS_DEP_TIME', 'ORIGIN_AIRPORT_ID', 'DEST_AIRPORT_ID',
        'ORIGIN_CITY_NAME', 'DEST_CITY_NAME', 'ARR_DELAY', 'AIRLINE_ID',
        'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'CARRIER', 'CRS_ARR_TIME',
        'FL_NUM', 'ORIGIN_STATE_ABR', 'DEST_STATE_ABR'],
       dtype='object'))

In [9]:
# References used in LinearDelayPredictor
list_ref = ['ORIGIN_CITY_NAME','DEST_CITY_NAME','ORIGIN_STATE_ABR','DEST_STATE_ABR']

list_quant = ['CRS_DEP_TIME']
#list_quant = None

list_target = ['ARR_DELAY']
#-------------------------------------------
# List of feautres excluded from encoding
#-------------------------------------------
list_excluded = list()
list_excluded.append('ORIGIN_AIRPORT_ID')
list_excluded.append('DEST_AIRPORT_ID')
list_excluded.append('ORIGIN_CITY_NAME')
list_excluded.append('DEST_CITY_NAME')
list_excluded.append('ARR_DELAY')
list_excluded.append('CARRIER')
list_excluded.append('CRS_ARR_TIME')
list_excluded.append('FL_NUM')
list_excluded.append('WEEK_OF_MONTH')
list_excluded.append('ORIGIN_STATE_ABR')
list_excluded.append('DEST_STATE_ABR')

list_value_excluded = ['FL','N707EV']
list_periodic_feature = None
#---------------------------------------------------------------------------------------------------------
# Record features transformation
#---------------------------------------------------------------------------------------------------------
oP4_ModelBuilder.dict_feature_processor = {'CRS_DEP_TIME':LinearDelayPredictor.cb_convert_floathour_to_mn}
# Values form CRS_DEP_TIME will be converted into mn then hour using 2 successives callback functions.
#dict_feature_processor = {'CRS_DEP_TIME':[cb_convert_floathour_to_mn]}
#oP4_ModelBuilder.dict_feature_processor = dict_feature_processor.copy()
t0 = time.time()

oP4_ModelBuilder.data_build(list_ref, list_quant, list_target,list_excluded\
                            ,list_value_excluded=list_value_excluded\
                           ,list_periodic_feature = list_periodic_feature,
                           list_for_user_test = list_for_user_test)
t1 = time.time()
print("\n*** Elapsed time = %0.2F" %(t1-t0))
oP4_ModelBuilder.print()


 *** 1 Shape =  (433298, 15)
***INFO _list_store() : list_periodic_feature is None

*** _model_preprocessing() : Index(['CRS_DEP_TIME', 'ORIGIN_AIRPORT_ID', 'DEST_AIRPORT_ID',
       'ORIGIN_CITY_NAME', 'DEST_CITY_NAME', 'ARR_DELAY', 'AIRLINE_ID',
       'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'CARRIER', 'CRS_ARR_TIME',
       'FL_NUM', 'ORIGIN_STATE_ABR', 'DEST_STATE_ABR', 'ORIGIN_CLIMAT',
       'DEST_CLIMAT'],
      dtype='object')
Pourcent valeurs outliers écrêtées : 8.80


/home/bangui/Dropbox/Perso/Formation/Openclassroom/Datascientist/P4/P4_ModelBuilder.py:1542: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if value_excluded in self._df[self._list_qualitative].values[:, col_num] :



 *** _data_for_computation() : encoding features= ['AIRLINE_ID', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'ORIGIN_CLIMAT', 'DEST_CLIMAT']

*** Route= 255:1/354 Encoding ...

*** Route= 2676:2/354 Encoding ...

*** Route= 961:3/354 Encoding ...

*** Route= 2318:4/354 Encoding ...

*** Route= 3626:5/354 Encoding ...

*** Route= 3104:6/354 Encoding ...

*** Route= 2850:7/354 Encoding ...

*** Route= 1589:8/354 Encoding ...

*** Route= 954:9/354 Encoding ...

*** Route= 893:10/354 Encoding ...

*** Route= 439:11/354 Encoding ...

*** Route= 617:12/354 Encoding ...

*** Route= 1560:13/354 Encoding ...

*** Route= 3490:14/354 Encoding ...

*** Route= 3543:15/354 Encoding ...

*** Route= 635:16/354 Encoding ...

*** Route= 3186:17/354 Encoding ...

*** Route= 897:18/354 Encoding ...

*** Route= 3323:19/354 Encoding ...

*** Route= 1994:20/354 Encoding ...

*** Route= 662:21/354 Encoding ...

*** Route= 1200:22/354 Encoding ...

*** Route= 1004:23/354 Encoding ...

*** Route= 2196:24/354 Encod


*** Route= 2800:242/354 Encoding ...

*** Route= 1517:243/354 Encoding ...

*** Route= 2093:244/354 Encoding ...

*** Route= 2497:245/354 Encoding ...

*** Route= 1347:246/354 Encoding ...

*** Route= 1379:247/354 Encoding ...

*** Route= 1960:248/354 Encoding ...

*** Route= 3079:249/354 Encoding ...

*** Route= 2562:250/354 Encoding ...

*** Route= 350:251/354 Encoding ...

*** Route= 2617:252/354 Encoding ...

*** Route= 2156:253/354 Encoding ...

*** Route= 2978:254/354 Encoding ...

*** Route= 1883:255/354 Encoding ...

*** Route= 2367:256/354 Encoding ...

*** Route= 1875:257/354 Encoding ...

*** Route= 458:258/354 Encoding ...

*** Route= 1003:259/354 Encoding ...

*** Route= 551:260/354 Encoding ...

*** Route= 926:261/354 Encoding ...

*** Route= 3456:262/354 Encoding ...

*** Route= 2910:263/354 Encoding ...

*** Route= 1756:264/354 Encoding ...

*** Route= 3146:265/354 Encoding ...

*** Route= 485:266/354 Encoding ...

*** Route= 862:267/354 Encoding ...

*** Route= 2303:2

In [10]:
len(oP4_ModelBuilder._dict_route_data)

353

In [11]:
oP4_ModelBuilder.print()


-------------------------------------------------------------
Data set year : ......................... : 2016
Low memory flag : ....................... : True
Data model dimensions : ................. :(394769, 0)
Route in model : ........................ : True
Removing outliers : ..................... : True
Percent removed outliers : .............. : 8.80
Split delay config ...................... : {'neg': 0, 'pos': 0}
Carrier in model : ...................... : False

Qualitative features list ............... : ['AIRLINE_ID', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'ORIGIN_CLIMAT', 'DEST_CLIMAT']
Quantitative features list .............. : ['CRS_DEP_TIME']
Target features list .................... : ['ARR_DELAY']
Excluded features list .................. : ['ORIGIN_AIRPORT_ID', 'DEST_AIRPORT_ID', 'ORIGIN_CITY_NAME', 'DEST_CITY_NAME', 'ARR_DELAY', 'CARRIER', 'CRS_ARR_TIME', 'FL_NUM', 'WEEK_OF_MONTH', 'ORIGIN_STATE_ABR', 'DEST_STATE_ABR']
Periodic features list .................. :

In [52]:
file_data_dumped = "./data/oP4_ModelBuilder_data_build.dump"

In [53]:
import P4_ModelBuilder

print("\n*** Dumping oP4_ModelBuilder after data_build()...")
P4_ModelBuilder.dump_me(oP4_ModelBuilder,file_data_dumped)
print("*** Done!\n")


*** Dumping oP4_ModelBuilder after data_build()...
*** Done!



In [79]:
import P4_ModelBuilder

print("\n*** Reloading oP4_ModelBuilder...")
oP4_ModelBuilder = P4_ModelBuilder.reloadme(file_data_dumped)
print("*** Done!\n")


*** Reloading oP4_ModelBuilder...
*** Done!



## <font color='blue'>Méthode *model_build()*</font>

In [62]:
import P4_ModelBuilder
from P4_ModelBuilder import *

n_alphas = 20
dict_parameters_ridge = {'n_alphas':n_alphas,'list_alphas': np.logspace(1, 2, n_alphas)}
dict_parameters_lasso = {'n_alphas':n_alphas,'list_alphas': np.logspace(-5, 5, n_alphas)}

list_alphas_sgdreg =  {'max_iter':[5, 10, 20, 40], 'penalty':[None, "l1", "l2", "elasticnet"]\
         , "alpha":[0.0001, 0.001, 0.01]\
         , "l1_ratio": [0.15, 0.5, 0.85] }
dict_parameters_sgdreg= {'n_alphas':None,'list_alphas':list_alphas_sgdreg}

dict_models_parameters = dict()
dict_models_parameters['SGDRegressor'] = dict_parameters_sgdreg
if False :
    dict_models_parameters['DummyRegressor'] = None
    dict_models_parameters['LinearRegression'] = None
    dict_models_parameters['Lasso'] = dict_parameters_lasso
    dict_models_parameters['Ridge'] = dict_parameters_ridge
    dict_models_parameters['SGDRegressor'] = dict_parameters_sgdreg
t0 = time.time()
oP4_ModelBuilder._model_build(dict_models_parameters)
t1 = time.time()

print("\n *** Elapsed time = %1.2F"%(t1-t0))

#oP4_ModelBuilder_save = P4_ModelBuilder(None,None)
#oP4_ModelBuilder_save.copy(oP4_ModelBuilder)

Route=255 : 1/353: Elapsed time = 0.92
Route=2676 : 2/353: Elapsed time = 0.97
Route=961 : 3/353: Elapsed time = 0.91
Route=2318 : 4/353: Elapsed time = 0.92
Route=3626 : 5/353: Elapsed time = 0.94
Route=3104 : 6/353: Elapsed time = 0.85
Route=2850 : 7/353: Elapsed time = 0.93
Route=1589 : 8/353: Elapsed time = 1.69
Route=954 : 9/353: Elapsed time = 1.62
Route=893 : 10/353: Elapsed time = 1.38
Route=439 : 11/353: Elapsed time = 2.05
Route=617 : 12/353: Elapsed time = 1.41
Route=1560 : 13/353: Elapsed time = 0.94
Route=3490 : 14/353: Elapsed time = 1.04
Route=3543 : 15/353: Elapsed time = 1.13
Route=635 : 16/353: Elapsed time = 1.15
Route=3186 : 17/353: Elapsed time = 2.11
Route=897 : 18/353: Elapsed time = 1.25
Route=3323 : 19/353: Elapsed time = 0.95
Route=1994 : 20/353: Elapsed time = 1.35
Route=662 : 21/353: Elapsed time = 1.62
Route=1200 : 22/353: Elapsed time = 1.07
Route=1004 : 23/353: Elapsed time = 1.00
Route=2196 : 24/353: Elapsed time = 1.20
Route=912 : 25/353: Elapsed time =

Route=2211 : 201/353: Elapsed time = 1.16
Route=1437 : 202/353: Elapsed time = 6.32
Route=1915 : 203/353: Elapsed time = 0.82
Route=972 : 204/353: Elapsed time = 0.87
Route=1584 : 205/353: Elapsed time = 0.88
Route=1774 : 206/353: Elapsed time = 0.96
Route=913 : 207/353: Elapsed time = 1.24
Route=3262 : 208/353: Elapsed time = 1.09
Route=3195 : 209/353: Elapsed time = 1.50
Route=3422 : 210/353: Elapsed time = 1.28
Route=2935 : 211/353: Elapsed time = 0.84
Route=2482 : 212/353: Elapsed time = 1.09
Route=1701 : 213/353: Elapsed time = 1.35
Route=1459 : 214/353: Elapsed time = 1.11
Route=3557 : 215/353: Elapsed time = 1.15
Route=991 : 216/353: Elapsed time = 1.98
Route=648 : 217/353: Elapsed time = 1.89
Route=1514 : 218/353: Elapsed time = 1.83
Route=155 : 219/353: Elapsed time = 1.14
Route=740 : 220/353: Elapsed time = 1.07
Route=2044 : 221/353: Elapsed time = 0.94
Route=650 : 222/353: Elapsed time = 1.39
Route=2327 : 223/353: Elapsed time = 0.99
Route=103 : 224/353: Elapsed time = 1.01


** Dumping model issued from <font color='blue'>*oP4_ModelBuilder*</font> **

In [63]:
import P4_ModelBuilder

print("\n*** Dumping oP4_ModelBuilder after model_build()...")
P4_ModelBuilder.dump_me(oP4_ModelBuilder,"./data/oP4_ModelBuilder_model_build.dump")
print("*** Done!\n")


*** Dumping oP4_ModelBuilder after model_build()...
*** Done!



** Dumping <font color='blue'>*LinearDelayPredictor*</color> **

In [80]:
#oP4_ModelBuilder._print_result()
oP4_ModelBuilder.frac_test = -1
oP4_ModelBuilder.predictor_dump()


 *** Fraction of user test dataframe: size= (395, 13)

 *** Route dataframe compression...

 *** User test dataframe compression...

 *** Data route compression...

 *** Dump object in file= ./data/oLinearDelayPredictor.dump...

 *** Route dataframe decompression ...

 *** User dataframe decompression ...

 *** User dataframe decompression ...


In [65]:
oP4_ModelBuilder.oLinearDelayPredictor._df_route

ORIGIN_CITY_NAME                  DEST_CITY_NAME  HROUTE
353625                      Austin, TX                   Baltimore, MD     255
139061                Palm Springs, CA                     Phoenix, AZ    2676
30344            Dallas/Fort Worth, TX                       Omaha, NE     961
348703                   Nashville, TN                       Tampa, FL    2318
374571  West Palm Beach/Palm Beach, FL                   Baltimore, MD    3626
87504                  San Antonio, TX                     Seattle, WA    3104
245196                    Portland, OR                   Anchorage, AK    2850
125313                     Houston, TX                 Los Angeles, CA    1589
31076            Dallas/Fort Worth, TX                   Nashville, TN     954
432694                      Dallas, TX                  Washington, DC     893
1070                        Boston, MA                    New York, NY     439
443932                     Chicago, IL                   Baltimore, MD     617
313581                     Houston, TX                     Detroit, MI    1560
38008                        Tampa, FL           Dallas/Fort Worth, TX    3490
170970                      Tucson, AZ                     Houston, TX    3543
402075                     Chicago, IL                      Dallas, TX     635
351089               San Francisco, CA                 Los Angeles, CA    3186
259363           Dallas/Fort Worth, TX                     Atlanta, GA     897
147433                     Seattle, WA                       Boise, ID    3323
85719                  Los Angeles, CA                    Portland, OR    1994
189071                     Chicago, IL                     Houston, TX     662
237807                     Detroit, MI                   Milwaukee, WI    1200
202900                      Dayton, OH                     Detroit, MI    1004
281084                 Minneapolis, MN                   Milwaukee, WI    2196
13618            Dallas/Fort Worth, TX                      Dayton, OH     912
419850                     Burbank, CA                     Oakland, CA     492
329032                Indianapolis, IN                     Chicago, IL    1653
392487                      Denver, CO                   St. Louis, MO    1125
433159             Fort Lauderdale, FL                 New Orleans, LA    1336
232133                     Atlanta, GA                     Memphis, TN     181
...                                ...                             ...     ...
13715            Dallas/Fort Worth, TX                      Denver, CO     913
235791                 Minneapolis, MN                   St. Louis, MO    2233
311107                     Roanoke, VA                     Atlanta, GA    2960
34803               Salt Lake City, UT           Dallas/Fort Worth, TX    3023
3552                         Miami, FL                 Los Angeles, CA    2086
239592                     Atlanta, GA                    Columbus, OH     129
353121               San Francisco, CA               Arcata/Eureka, CA    3152
290533                      Laredo, TX           Dallas/Fort Worth, TX    1822
338311                   San Diego, CA                     Phoenix, AZ    3138
164428               Mammoth Lakes, CA               San Francisco, CA    2040
243281                     Chicago, IL                     Atlanta, GA     615
424107                     Chicago, IL                   St. Louis, MO     733
46677                  Los Angeles, CA                     Phoenix, AZ    1992
169622               San Francisco, CA                        Reno, NV    3209
358248                     Phoenix, AZ                   San Diego, CA    2800
16886                   Sacramento, CA           Dallas/Fort Worth, TX    2982
291083                  Valparaiso, FL           Dallas/Fort Worth, TX    3573
437599                   Santa Ana, CA                      Denver, CO    3276
32515                   Washington, DC           Dallas/Fort Worth, TX  

** Loading model issued from <font color='blue'>*oP4_ModelBuilder*</font> **

In [ ]:
oP4_ModelBuilder.print()

# <font color='blus'> Test de l'application de prédiction</font>

In [81]:
import LinearDelayPredictor
oLinearDelayPredictor = LinearDelayPredictor.LinearDelayPredictor()
if True :
    oLinearDelayPredictor_reloaded = LinearDelayPredictor.load_dumped()
    oLinearDelayPredictor.copy(oLinearDelayPredictor_reloaded)
    
else :
    oLinearDelayPredictor = oP4_ModelBuilder._oLinearDelayPredictor
#oLinearDelayPredictor.print()
#oLinearDelayPredictor.dump()

#oLinearDelayPredictor.model_name = 'DummyRegressor'


In [82]:
oLinearDelayPredictor._df_route.shape

(395, 3)

In [68]:
oLinearDelayPredictor.get_random_flights(10)

CRS_DEP_TIME       ORIGIN_CITY_NAME         DEST_CITY_NAME  ARR_DELAY  \
56665           1200             Boston, MA           New York, NY          4   
264983           805           New York, NY              Miami, FL        -20   
328556          1047        Little Rock, AR            Chicago, IL         -3   
422974          2100         Louisville, KY          Baltimore, MD        -15   
287540          1315         Pittsburgh, PA            Atlanta, GA         13   
244141          1720         Pittsburgh, PA            Phoenix, AZ        -13   
23232           1050  Dallas/Fort Worth, TX            Atlanta, GA        -14   
81480           1100            Seattle, WA        New Orleans, LA        -20   
261227          1512           New York, NY  Dallas/Fort Worth, TX        -42   
233262           725            Atlanta, GA           Columbus, OH         -4   

        AIRLINE_ID  MONTH  DAY_OF_MONTH  DAY_OF_WEEK CARRIER  CRS_ARR_TIME  \
56665        19805      1            11            1      AA          1316   
264983       19790      1            21            4      DL          1126   
328556       20366      1            17            7      EV          1243   
422974       19393      1             6            3      WN          2235   
287540       19790      1            31            7      DL          1514   
244141       19805      1            29            5      AA          2006   
23232        19805      1             2            6      AA          1357   
81480        19930      1            22            5      AS          1739   
261227       19790      1            13            3      DL          1841   
233262       19790      1             7            4      DL           854   

        FL_NUM ORIGIN_STATE_ABR DEST_STATE_ABR  
56665     2136               MA             NY  
264983    2190               NY             FL  
328556    5903               AR             IL  
422974    2243               KY             MD  
287540    1599               PA             GA  
244141     586               PA             AZ  
23232     1442               TX             GA  
81480      788               WA             LA  
261227    2180               NY             TX  
233262    1681               GA             OH

In [69]:
#oLinearDelayPredictor._get_route("Louisville, KY","Baltimore, MD")
#oLinearDelayPredictor._df_route[oLinearDelayPredictor._df_route['ORIGIN_CITY_NAME'] == "Louisville, KY"]
oLinearDelayPredictor._df_route.sample()

ORIGIN_CITY_NAME DEST_CITY_NAME  HROUTE
424006      Chicago, IL  Las Vegas, NV     674

In [70]:
for test_count in range(1,20,1) :
    #df_param = oLinearDelayPredictor._df_user_test.sample(1)
    df_param = oLinearDelayPredictor.get_random_flights(10)
    if df_param is None :
        print("\n*** ERROR : no data with available routes! ")
        break
    #df_param = oLinearDelayPredictor._df_user_test.sample(1)
    #df_param = oLinearDelayPredictor._df_user_test.copy()
    #origin, destination = oP4_ModelBuilder._get_route()
    #print(origin, destination)
    index_row = df_param.index[0]
    month=df_param.loc[index_row,'MONTH']
    
    day_of_month=df_param.loc[index_row,'DAY_OF_MONTH']
    day_of_week=df_param.loc[index_row,'DAY_OF_WEEK']
    crs_dep_time = df_param.loc[index_row,'CRS_DEP_TIME']
    
    airline_id = df_param.loc[index_row,'AIRLINE_ID']
    arr_delay = df_param.loc[index_row,'ARR_DELAY']

    origin_city_name = df_param.loc[index_row,'ORIGIN_CITY_NAME']
    dest_city_name = df_param.loc[index_row,'DEST_CITY_NAME']

    origin_state_abr = df_param.loc[index_row,'ORIGIN_STATE_ABR']
    dest_state_abr = df_param.loc[index_row,'DEST_STATE_ABR']
    
    
    print("Month             = {}".format(month))
    print("Day Of Month      = {}".format(day_of_month))
    print("Day Of Week       = {}".format(day_of_week))
    print("Depart time       = {}".format(crs_dep_time))
    print("Airline ID        = {}".format(airline_id))
    print("Origin            = {}".format(origin_city_name))
    print("Destination       = {}".format(dest_city_name))
    print("Origin state      = {}".format(origin_state_abr))
    print("Destination state = {}".format(dest_state_abr))

    route = oLinearDelayPredictor._get_route(origin_city_name,dest_city_name)

    #print("Route  = {}\n".format(route))
    
    list_qualitative = [airline_id, month, day_of_month, day_of_week, origin_state_abr, dest_state_abr]
    list_quantitative = [crs_dep_time]
    list_route = [origin_city_name,dest_city_name]
    oLinearDelayPredictor.model_name = 'SGDRegressor'
    
    result_delay, dict_result_delay \
    = oLinearDelayPredictor._forecast_delay(list_qualitative,list_quantitative, list_route,is_all_model=False)
    #print(dict_result_delay,result_delay)
    if dict_result_delay is not None :
        dict_result_delay['measure'] = arr_delay
        #print("")
        #print("Measured delay for flight : %1.2F" %arr_delay)
        LinearDelayPredictor.print_delays(dict_result_delay)
        #print("dict_result_delay = {}".format(dict_result_delay ))
    else :
        print("\n*** ERROR : delay evaluation FAILED!")

    

Month             = 1
Day Of Month      = 21
Day Of Week       = 4
Depart time       = 701
Airline ID        = 19790
Origin            = Minneapolis, MN
Destination       = Tampa, FL
Origin state      = MN
Destination state = FL

----- Results--------
Model = SGDRegressor : Delay for flight = -5.58
Model = measure : Delay for flight = -9.00
----- Results--------

Month             = 1
Day Of Month      = 30
Day Of Week       = 6
Depart time       = 706
Airline ID        = 19805
Origin            = San Jose, CA
Destination       = Dallas/Fort Worth, TX
Origin state      = CA
Destination state = TX

----- Results--------
Model = SGDRegressor : Delay for flight = -17.04
Model = measure : Delay for flight = -15.00
----- Results--------

Month             = 1
Day Of Month      = 3
Day Of Week       = 7
Depart time       = 2155
Airline ID        = 19805
Origin            = Dallas/Fort Worth, TX
Destination       = Reno, NV
Origin state      = TX
Destination state = NV

----- Results--------


# <font color='blue'>Calcul de la moyenne pondérée par route</font>

** <font color='blue'>Calcul de la fréquence par route</font>**

In [92]:
sum_frequency =0
model_name = 'SGDRegressor'
error = 0.0
error_r2 = 0.0
list_error_route = list()
ser_route = oP4_ModelBuilder.oLinearDelayPredictor._df_route.HROUTE.value_counts()
for route in oP4_ModelBuilder._dict_route_data.keys() :
    frequency = 0
    
    if oP4_ModelBuilder._dict_route_data[route] is not None :
        if 'result' in oP4_ModelBuilder._dict_route_data[route].keys() :
            if 4 < ser_route[route] :
                #print(ser_route[route])
                sum_frequency += ser_route[route]
                error += oP4_ModelBuilder._dict_route_data[route]['result']['SGDRegressor']['MAE']*ser_route[route]
                error_r2 += oP4_ModelBuilder._dict_route_data[route]['result']['SGDRegressor']['R2']*ser_route[route]
        else :
            list_error_route.append(route)
    else :
        pass
    #print(error)

if 0 < sum_frequency :
    print("\n*** MAE pondéré= "+str(error/sum_frequency))
    print("\n*** R2 pondéré= "+str(error_r2/sum_frequency))
    print("\n*** Nb routes en erreur : "+str(len(list_error_route)))
else :
    print("\n*** ERREUR:calcul de la moyenne pondérée impossible!\n")
    
#oP4_ModelBuilder._dict_route_data[3089]
#error pondérée LinearRegression = 11.0666749545948


*** MAE pondéré= 9.180120754244452

*** R2 pondéré= 0.04687120344049989

*** Nb routes en erreur : 0


oP4_ModelBuilder._dict_route_data[3089]['result']['SGDRegressor']

In [88]:
oP4_ModelBuilder.oLinearDelayPredictor._df_user_test.shape, len(oP4_ModelBuilder._dict_route_data)

((395, 13), 353)

In [91]:
oP4_ModelBuilder.oLinearDelayPredictor._df_route.HROUTE.value_counts()

439     5
897     3
2813    2
2876    2
129     2
3186    2
2211    2
3183    2
1607    2
1958    2
3276    2
3477    2
575     2
1602    2
972     2
2606    2
574     2
1992    2
2726    2
1986    2
1653    2
3372    2
817     2
2704    2
1200    2
131     2
3079    2
3594    2
678     2
2812    2
       ..
1379    1
3125    1
2750    1
183     1
1384    1
1386    1
3242    1
1310    1
2901    1
1873    1
3624    1
3407    1
2355    1
1789    1
2978    1
2871    1
1336    1
1338    1
827     1
2365    1
2367    1
1347    1
1822    1
2373    1
1351    1
1864    1
492     1
1355    1
845     1
243     1
Name: HROUTE, Length: 354, dtype: int64